### ISSUE TITLE
Add `features=features` otherwise feature argument is not used.

### ISSUE THREAD

**Issue by MuhammedHasan** [openvax/gtfparse#18]
https://github.com/openvax/gtfparse/blob/c79cab0c2a5ac3d08de9f932fa29a56d334a712b/gtfparse/read_gtf.py#L213

**Comment by littleblackfish** [comment]
Issue is still present.

**Comment by Lea-Meunier** [comment]
Issue is still present, missing features option in the `read_gtf` function of the file `read_gtf.py` at line 207.

Modification to solve the issue:
```
if expand_attribute_column:
    result_df = parse_gtf_and_expand_attributes(
        filepath_or_buffer,
        chunksize=chunksize,
        restrict_attribute_columns=usecols,
        features=features)
```
