### ISSUE TITLE
consider switching to pytest

### ISSUE THREAD

**Issue by mdb571** [openvax/gtfparse#29]
Hello,

We have a Debian bug report [#1018506](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018506)  affecting gtfparse package. Since [nose](https://github.com/nose-devs/nose/commit/0f40fa995384afad) is deprecated , Debian is gradually moving to remove support for nose. Just wanted to give you heads up so that you can work on this. :)

Thanks

**Comment by gamazeps** [comment]
@iskandr should be closed, since you did the change ?

**Comment by iskandr** [comment]
You're right, sorry I forgot to clean these up.
